version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb+srv://nikhilsharma110994:nikhil@training-cluster.vd7tsre.mongodb.net/?retryWrites=true&w=majority&appName=training-cluster
    command: npm start

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
